--- #YAML:1.0
name:               XS-TCC
version:            0.04
abstract:           Embed, wrap & compile C code in Perl without going to disk
author:
    - Steffen Mueller <smueller@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    Alien::TinyCC:        0.03
    Cwd:                  0
    ExtUtils::MakeMaker:  0
    File::Basename:       0
    File::Spec:           0
    Getopt::Long:         0
build_requires:
    Test::More:  0.88
requires:
    ExtUtils::Embed:     0
    ExtUtils::ParseXS:   3.21
    ExtUtils::Typemaps:  3.21
    File::ShareDir:      0
    File::Spec:          0
    perl:                5.008
    XSLoader:            0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
